apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights
  template:
    metadata:
      labels:
        app: flights
    spec:
      containers:
      - name: flights
        image: cronodan32/flights:latest
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: flights-service
spec:
  type: NodePort
  selector:
    app: flights
  ports:
    - port: 81
      targetPort: 81
      nodePort: 30001