apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: cronodan32/home:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  type: NodePort
  selector:
    app: home
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002