apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
      - name: host
        image: cronodan32/host:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: host-service
spec:
  type: NodePort
  selector:
    app: host
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004