apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
      - name: hotels
        image: cronodan32/hotels:latest
        ports:
        - containerPort: 82
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-service
spec:
  type: NodePort
  selector:
    app: hotels
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003